database:
    db_connection_file: 'dbconnection.json'
csv_paths:
    training_paths: 'training_qrcodes.csv'
    testing_paths: 'testing_qrcodes.csv'
scans:
    scan_amount : 5000
    realtime : True
calibration:
    calibration_file: 'depthmap_toolkit/camera_calibration.txt'
data:
    dataset: 'anon-pcd-version5.0'
paths:
    source_path: '/mnt/bmzdata/cgminbmzprod_v5.0/'
    target_path: 'dataset/'
